from __future__ import annotations

import http.cookiejar
import os
import secrets
import stat
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

REQUIRED_COOKIES = ("a1", "web_session")


class CookieExportError(RuntimeError):
    """A safe cookie publication error that never includes cookie values."""


def _clean_field(value: Any, field: str) -> str:
    result = str(value or "")
    if not result or any(character in result for character in "\t\r\n\0"):
        raise CookieExportError(f"invalid cookie {field}")
    return result


def _is_xiaohongshu_domain(domain: str) -> bool:
    normalized = domain.lstrip(".").lower()
    return normalized == "xiaohongshu.com" or normalized.endswith(".xiaohongshu.com")


def filter_xiaohongshu_cookies(
    cookies: Iterable[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for cookie in cookies:
        domain = str(cookie.get("domain") or "")
        if not _is_xiaohongshu_domain(domain):
            continue
        name = _clean_field(cookie.get("name"), "name")
        value = _clean_field(cookie.get("value"), "value")
        result.append(
            {
                "domain": _clean_field(domain, "domain"),
                "path": _clean_field(cookie.get("path") or "/", "path"),
                "name": name,
                "value": value,
                "secure": bool(cookie.get("secure")),
                "expires": cookie.get("expires"),
            }
        )
    return result


def validate_required_cookies(
    cookies: Iterable[Mapping[str, Any]],
) -> None:
    present = {str(cookie.get("name")) for cookie in cookies if cookie.get("value")}
    missing = [name for name in REQUIRED_COOKIES if name not in present]
    if missing:
        raise CookieExportError("required Xiaohongshu cookies are missing")


def netscape_cookie_bytes(
    cookies: Iterable[Mapping[str, Any]],
) -> bytes:
    filtered = filter_xiaohongshu_cookies(cookies)
    validate_required_cookies(filtered)
    lines = ["# Netscape HTTP Cookie File", "# Generated by xhs-session; do not edit."]
    for cookie in sorted(
        filtered,
        key=lambda item: (
            str(item["domain"]),
            str(item["path"]),
            str(item["name"]),
        ),
    ):
        domain = str(cookie["domain"])
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        try:
            expires = max(0, int(float(cookie.get("expires") or 0)))
        except (TypeError, ValueError, OverflowError):
            expires = 0
        lines.append(
            "\t".join(
                [
                    domain,
                    include_subdomains,
                    str(cookie["path"]),
                    "TRUE" if cookie["secure"] else "FALSE",
                    str(expires),
                    str(cookie["name"]),
                    str(cookie["value"]),
                ]
            )
        )
    return ("\n".join(lines) + "\n").encode("utf-8")


def validate_cookie_file(path: Path) -> None:
    try:
        metadata = path.lstat()
    except OSError as exc:
        raise CookieExportError("cookie file could not be validated") from exc
    if (
        stat.S_ISLNK(metadata.st_mode)
        or not stat.S_ISREG(metadata.st_mode)
        or stat.S_IMODE(metadata.st_mode) != 0o600
    ):
        raise CookieExportError("cookie file permissions are not 0600")
    jar = http.cookiejar.MozillaCookieJar()
    try:
        jar.load(path, ignore_discard=True, ignore_expires=True)
    except (OSError, http.cookiejar.LoadError) as exc:
        raise CookieExportError("cookie file format is invalid") from exc
    validate_required_cookies(
        {"name": cookie.name, "value": cookie.value}
        for cookie in jar
        if _is_xiaohongshu_domain(cookie.domain)
    )


def atomic_export_cookies(
    cookie_path: Path,
    cookies: Iterable[Mapping[str, Any]],
) -> None:
    payload = netscape_cookie_bytes(cookies)
    cookie_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = cookie_path.parent / f".{cookie_path.name}.{secrets.token_hex(8)}.tmp"
    descriptor = os.open(
        temporary,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(0o600)
        validate_cookie_file(temporary)
        os.replace(temporary, cookie_path)
        cookie_path.chmod(0o600)
        directory_fd = os.open(cookie_path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except OSError as exc:
        raise CookieExportError("cookie file could not be published") from exc
    finally:
        temporary.unlink(missing_ok=True)
