from __future__ import annotations

import http.cookiejar
import os
import secrets
import stat
from collections.abc import Iterable
from pathlib import Path

REQUIRED_COOKIES = {"SESSDATA", "bili_jct", "DedeUserID"}


class CookieExportError(RuntimeError):
    """A safe Bilibili cookie publication error."""


def _is_bilibili_domain(domain: str) -> bool:
    value = domain.lstrip(".").lower()
    return value == "bilibili.com" or value.endswith(".bilibili.com")


def _cookie_lines(cookies: Iterable[http.cookiejar.Cookie]) -> bytes:
    selected = [
        cookie for cookie in cookies
        if cookie.value and _is_bilibili_domain(cookie.domain)
    ]
    present = {cookie.name for cookie in selected}
    if not REQUIRED_COOKIES <= present:
        raise CookieExportError("required Bilibili cookies are missing")
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by bilibili-session; do not edit.",
    ]
    for cookie in sorted(
        selected,
        key=lambda item: (item.domain, item.path, item.name),
    ):
        lines.append("\t".join([
            cookie.domain,
            "TRUE" if cookie.domain.startswith(".") else "FALSE",
            cookie.path or "/",
            "TRUE" if cookie.secure else "FALSE",
            str(max(0, int(cookie.expires or 0))),
            cookie.name,
            cookie.value,
        ]))
    return ("\n".join(lines) + "\n").encode()


def validate_cookie_file(path: Path) -> None:
    try:
        metadata = path.lstat()
    except OSError as exc:
        raise CookieExportError("cookie file could not be validated") from exc
    if (
        stat.S_ISLNK(metadata.st_mode)
        or not stat.S_ISREG(metadata.st_mode)
        or stat.S_IMODE(metadata.st_mode) != 0o600
    ):
        raise CookieExportError("cookie file permissions are not 0600")
    jar = http.cookiejar.MozillaCookieJar()
    try:
        jar.load(path, ignore_discard=True, ignore_expires=True)
    except (OSError, http.cookiejar.LoadError) as exc:
        raise CookieExportError("cookie file format is invalid") from exc
    if not REQUIRED_COOKIES <= {
        cookie.name for cookie in jar
        if cookie.value and _is_bilibili_domain(cookie.domain)
    }:
        raise CookieExportError("required Bilibili cookies are missing")


def atomic_export_cookies(
    path: Path,
    cookies: Iterable[http.cookiejar.Cookie],
) -> None:
    payload = _cookie_lines(cookies)
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    path.parent.chmod(0o700)
    temporary = path.parent / f".{path.name}.{secrets.token_hex(8)}.tmp"
    descriptor = os.open(
        temporary,
        os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
        0o600,
    )
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        validate_cookie_file(temporary)
        os.replace(temporary, path)
        path.chmod(0o600)
    except OSError as exc:
        raise CookieExportError("cookie file could not be published") from exc
    finally:
        temporary.unlink(missing_ok=True)
